### ISSUE TITLE
Pressing ENTER after </html> causes TypeError: Cannot read property 'mark' of null

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#331]
The HTMLInstrumention in Brackets doesn't seem to like you moving beyond the end of the `<html>...</html> <-- here` content with the cursor.

STR:
- go to https://mozillathimblelivepreview.net/bramble/dist/
- move your cursor to the end of `</html>`
- press ENTER
- look at console

```
Exception in 'change' listener on Document {file: File, language: Language, _refreshInProgress: false, _text: null, diskTimestamp: Sat May 30 2015 13:36:42 GMT-0400 (EDT)…} TypeError: Cannot read property 'mark' of null TypeError: Cannot read property 'mark' of null
    at _getMarkerAtDocumentPos (http://localhost:8000/src/LiveDevelopment/MultiBrowserImpl/language/HTMLInstrumentation.js:162:21)
    at Builder.DOMUpdater (http://localhost:8000/src/LiveDevelopment/MultiBrowserImpl/language/HTMLInstrumentation.js:263:33)
    at _updateDOM (http://localhost:8000/src/LiveDevelopment/MultiBrowserImpl/language/HTMLInstrumentation.js:525:23)
    at Object.getUnappliedEditList (http://localhost:8000/src/LiveDevelopment/MultiBrowserImpl/language/HTMLInstrumentation.js:586:22)
    at LiveHTMLDocument._onChange (http://localhost:8000/src/LiveDevelopment/MultiBrowserImpl/documents/LiveHTMLDocument.js:208:55)
    at Document.trigger (http://localhost:8000/src/utils/EventDispatcher.js:222:40)
    at Document._notifyDocumentChange (http://localhost:8000/src/document/Document.js:287:14)
    at Document._handleEditorChange (http://localhost:8000/src/document/Document.js:427:14)
    at Editor.trigger (http://localhost:8000/src/utils/EventDispatcher.js:222:40)
    at http://localhost:8000/src/editor/Editor.js:876:18
```

Not a huge problem, but noisy on the console.

cc @busykai

**Comment by edyedy123** [comment]
Hey, I'd like to give this a try.

**Comment by humphd** [comment]
https://github.com/mozilla/brackets/issues/716 is probably going to be easier.
