### ISSUE TITLE
Failed at the bramble@1.9.0-0 build script 'grunt build-browser

### ISSUE THREAD

**Issue by anephew** [mozilla/brackets#764]
### Description

Trying to setup Bramble on my local machine.

### Steps to Reproduce

1. npm install --no-optional / good
2. npm run build / failed

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bramble@1.9.0-0~prebuild: bramble@1.9.0-0
6 silly lifecycle bramble@1.9.0-0~prebuild: no script for prebuild, continuing
7 info lifecycle bramble@1.9.0-0~build: bramble@1.9.0-0
8 verbose lifecycle bramble@1.9.0-0~build: unsafe-perm in lifecycle true
9 verbose lifecycle bramble@1.9.0-0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;d:\LOCALHOST\Bramble\brackets\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Installed\Audio\LiquidSonics\Reverberate (x64)\Resources;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;D:\PROGRAMS\INTERNET\Youtube-dl\;D:\PROGRAMS\INTERNET\Wget\;C:\Program Files (x86)\Livestreamer;C:\Program Files (x86)\VideoLAN\;D:\PROGRAMS\Dev\Zeal Dev\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;c:\Users\anephew\AppData\Local\Android\sdk\platform-tools\;D:\PROGRAMS\INTERNET\WinSCP\;c:\Program Files (x86)\Installed\Dev\Git\cmd;D:\PROGRAMS\Dev\Brackets 0.45\command;C:\Program Files (x86)\Installed\Other\Skype\Phone\;C:\Program Files\nodejs\;C:\Ruby23-x64\bin;C:\Users\anephew\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\HMA! Pro VPN\bin;C:\Users\anephew\AppData\Local\atom\bin;C:\Users\anephew\AppData\Local\Microsoft\WindowsApps;C:\Users\anephew\AppData\Roaming\npm
10 verbose lifecycle bramble@1.9.0-0~build: CWD: d:\LOCALHOST\Bramble\brackets
11 silly lifecycle bramble@1.9.0-0~build: Args: [ '/d /s /c', 'grunt build-browser' ]
12 silly lifecycle bramble@1.9.0-0~build: Returned: code: 3  signal: null
13 info lifecycle bramble@1.9.0-0~build: Failed to exec build script
14 verbose stack Error: bramble@1.9.0-0 build: `grunt build-browser`
14 verbose stack Exit status 3
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid bramble@1.9.0-0
16 verbose cwd d:\LOCALHOST\Bramble\brackets
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error bramble@1.9.0-0 build: `grunt build-browser`
22 error Exit status 3
23 error Failed at the bramble@1.9.0-0 build script 'grunt build-browser'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the bramble package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt build-browser
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs bramble
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls bramble
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

![image](https://cloud.githubusercontent.com/assets/551514/26279631/93bd675a-3dc1-11e7-8e3f-1af195632193.png)

Windows 10 x64 1703 (15063.296)

**Comment by humphd** [comment]
Thanks for filing this, and sorry you're having issues.  The problem appears to be that we're doing `rm` [here](https://github.com/mozilla/brackets/blob/master/Gruntfile.js#L410), which won't work on Windows.  We should switch to a node.js version of rm.

cc @Pomax

**Comment by Pomax** [comment]
@humphd if these were npm scripts I'd recommend using `shx` instead, since that acts as a cross-platform front door for common unix tools (so instead of "rm ..." you'd write "shx rm ..." and done). Given how this is structured, I'd kind of recommend making an npm task for this job, and then invoking that through grunt as `npm run clean:empty` or something, and then either use `rimraf` or `shx rm`
